### ISSUE TITLE
Is this package still under maintenance?

### ISSUE THREAD

**Issue by yuzumx** [jwiegley/regex-tool#6]
Hello

I am sorry to ask such a rude question, but this package seems to have not been updated for a long time.

So is this package still being maintained? If you have stopped maintenance, is there a similar package?

Thank you.

**Comment by jwiegley** [comment]
I'm not really maintaining it anymore, it's a perfectly fair question. :)

I recommend this, which is part of Emacs: https://www.masteringemacs.org/article/re-builder-interactive-regexp-builder

**Comment by yuzumx** [comment]
Thank you.

**Comment by purcell** [comment]
FWIW, I still use this package from time to time. :-)

**Comment by yuzumx** [comment]
@purcell 

Correct. In fact, I really think this package is much better than the current packages like `pcre2el`.

Just because of my obsessive-compulsive disorder, I want to remove the package that has not been updated for a long time.

**Comment by purcell** [comment]
> Just because of my obsessive-compulsive disorder, I want to remove the package that has not been updated for a long time.

I'd caution against that outlook -- why would updates be necessary for a small self-contained library like this? It's different in libraries that cooperate with lots of other packages, e.g. in web framework ecosystems, and perhaps you're more accustomed to that situation.
